### ISSUE TITLE
Practica 7_Despliegue en Heroku

### ISSUE THREAD

**Issue by dulce-blm** [SistemasTecTlaxiaco/practica-de-gps-equipo-nancy-brenda-belem#2]
[Practica 7_Despliegue en Heroku.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-gps-equipo-nancy-brenda-belem/files/8597556/Practica.7_Despliegue.en.Heroku.pdf)

**Comment by josealfredo79** [comment]
Muy bien hecho y revisado...

**Comment by josealfredo79** [comment]
La practica contiene todos los elementos pedidos en la rubrica, incluye portada, indice, ilustraciones, descripción etc.
calificacion: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
